### PR TITLE
add required config and Docs for Maven

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@EECOLOR currently available on JCenter and syncing to Maven central.

**Comment by EECOLOR** [comment]
Hey that's great! Thank you for putting in the effort and sorry for my lack of involvement.

So how would I release to maven? Previously I just typed `release` and the release plugin fixed it.

**Comment by graingert** [comment]
I'll add you to the bintray repo and configure the jcenter publish command
for this repo

**Comment by graingert** [comment]
@EECOLOR what's your bintray account?

**Comment by graingert** [comment]
@EECOLOR what's your bintray account?

**Comment by EECOLOR** [comment]
@graingert Sorry for the extreme late reaction.

My Bintray account name is `eecolor`

**Comment by EECOLOR** [comment]
@graingert Could you explain the process from the last commit before release to the library being available in maven central?

It seems the `publish` command will now publish to bintray. But how does the package go from bintray to central?

**Comment by EECOLOR** [comment]
@graingert Could you please answer my previous question?

**Comment by graingert** [comment]
Ah you just press the publish to Maven button

**Comment by EECOLOR** [comment]
@graingert I see, do you know (off the top of your head) if that can be automated?

**Comment by graingert** [comment]
@EECOLOR I don't know

**Comment by lucianenache** [comment]
@graingert  is there a reason why you've picked jcenter over maven central? Additionally it would be nice if we could integrate this with a travis or circleci build server.

**Comment by graingert** [comment]
@lucianeache I think you've misunderstood. Jcenter uploads to maven central

**Comment by lucianenache** [comment]
@graingert I understand that, but I was wondering why jcenter and not sonatype's nexus

**Comment by jorkzijlstra** [comment]
@graingert We just merged a different branch for releasing to Maven. Version 9.0.0 is now available on it.

**Pull request closed without merging**
