### PR TITLE
Updated to play 2.6 and Scala 2.12

### PR DESCRIPTION
**Pull request by n0tel**
#79 #74 Tests passed

### CODE REVIEW

**Comment by n0tel** [comment]
I think we can extend `AwsRequestHolder` from `AhcWSRequest` instead of `WSRequest`. Because with play2.6 many realization of method was removed from `WSRequest` and added to `AhcWSRequest`. (like get, put, post etc.)

But for now i just implements it inside `AwsRequestHolder`. What you think?

**Comment by EECOLOR** [comment]
@Hayena @jorkzijlstra Does one of you have time to integrate this?

**Comment by EECOLOR** [comment]
Oh and @n0tel thank you for the effort to create a pull request!

**Comment by lucianenache** [comment]
Hi, are there any plans on merging the PR ? If necessary I could help :)

**Comment by EECOLOR** [comment]
Hey @lucianenache,

it seems that @Hayena and @jorkzijlstra are on vacation or busy themselves. I could make you a contributor of the repository so you can do the merge and release. I myself do not have time to spend on this project at the moment.

A few things that are important (from the top of my head):
- Make sure a branch is created for the previous version (see other branches)
- Versioning, the version should go up semantically (see other releases for new play versions)
- The tests should be run and double-checked
- Code should be consistent with the rest of the library (no changes in conventions AND functionality)

If you think you can do it let me know and I'll add you as a contributor.

**Comment by lucianenache** [comment]
Hi, it would be nice to be able to maintain this project since it provides a pure implementation for s3 and I am already using it in a couple of projects. Therefore given the guidelines provided earlier I think I can help with maintaining the project.

**Comment by EECOLOR** [comment]
@lucianenache that's great! I've added you as a collaborator. Let me know if you have questions.

**Pull request merged**
